version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: airline-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: airline
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - airline-network

  airline-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airline-backend-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URI: mongodb://admin:password123@mongodb:27017/airline-backend?authSource=admin
      PORT: 3000
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - airline-network

volumes:
  mongodb_data:

networks:
  airline-network:
    driver: bridge